package com.github.juliarzymowska.plugin.api.providers;

import com.github.juliarzymowska.plugin.api.PromptTemplates;
import com.github.juliarzymowska.plugin.settings.AiExplainerSettingsState;
import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;

import java.net.URI;
import java.net.http.HttpRequest;

/**
 * Concrete implementation of the {@link BaseAiProvider} for Google's Gemini API.
 * <p>
 * This class handles the specific payload structures, endpoint URLs, and response
 * parsing required to communicate with the Gemini generative language models.
 */
public class GeminiProvider extends BaseAiProvider {

    private static final Gson gson = new Gson();

    /**
     * Constructs the HTTP request tailored for the Gemini API.
     * <p>
     * It dynamically retrieves the user-selected model from the plugin settings, constructs
     * the endpoint URL, and formats the prompt. If the source code context is missing,
     * it injects a fallback message to ensure the prompt remains coherent.
     *
     * @param errorMessage The raw error message or stack trace.
     * @param sourceCode   The contextual source code (can be null or empty).
     * @param apiKey       The Gemini API key.
     * @return A configured {@link HttpRequest} ready to be sent to Google's servers.
     */
    @Override
    protected HttpRequest buildHttpRequest(String errorMessage, String sourceCode, String apiKey) {
        // Fetch the model dynamically from the new map, falling back to the default if null
        String selectedModel = AiExplainerSettingsState.getInstance()
                .selectedModels.getOrDefault(AiProviderType.GEMINI.name(), AiProviderType.GEMINI.getSupportedModels().getFirst());

        String apiUrl = "https://generativelanguage.googleapis.com/v1beta/models/" + selectedModel + ":generateContent?key=" + apiKey;

        String finalSourceCode = (sourceCode != null && !sourceCode.trim().isEmpty())
                ? sourceCode
                : "No source code provided. Analyze based on the error message alone.";

        String formattedPrompt = String.format(PromptTemplates.ANALYZE_ERROR_PROMPT, errorMessage, finalSourceCode);

        JsonObject requestBody = buildRequestBody(formattedPrompt);

        return HttpRequest.newBuilder()
                .uri(URI.create(apiUrl))
                .header("Content-Type", "application/json")
                .POST(HttpRequest.BodyPublishers.ofString(gson.toJson(requestBody)))
                .build();
    }

    /**
     * Constructs the deeply nested JSON payload required by the Gemini API endpoint.
     * <p>
     * This includes setting up the {@code contents} array and applying specific
     * {@code generationConfig} parameters, such as a low temperature for deterministic
     * answers and enforcing the {@code application/json} response MIME type to guarantee
     * the LLM outputs valid JSON.
     *
     * @param formattedPrompt The final string prompt to be sent to the model.
     * @return A {@link JsonObject} representing the entire HTTP request body.
     */
    private JsonObject buildRequestBody(String formattedPrompt) {
        JsonObject part = new JsonObject();
        part.addProperty("text", formattedPrompt);

        JsonArray parts = new JsonArray();
        parts.add(part);

        JsonObject content = new JsonObject();
        content.add("parts", parts);

        JsonArray contents = new JsonArray();
        contents.add(content);

        JsonObject requestBody = new JsonObject();
        requestBody.add("contents", contents);

        JsonObject generationConfig = new JsonObject();
        generationConfig.addProperty("temperature", 0.2);
        generationConfig.addProperty("responseMimeType", "application/json");
        requestBody.add("generationConfig", generationConfig);

        return requestBody;
    }

    /**
     * Parses the highly nested JSON response returned by the Gemini API to extract
     * the generated text content.
     *
     * @param rawJsonResponse The raw JSON string returned by the HTTP response body.
     * @return The extracted text generated by the Gemini model.
     */
    @Override
    protected String parseResponse(String rawJsonResponse) {
        JsonObject jsonResponse = gson.fromJson(rawJsonResponse, JsonObject.class);
        return jsonResponse.getAsJsonArray("candidates")
                .get(0).getAsJsonObject()
                .getAsJsonObject("content")
                .getAsJsonArray("parts")
                .get(0).getAsJsonObject()
                .get("text").getAsString();
    }
}